### ISSUE TITLE
Move UJEP logo to the right side?

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#12]
from
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/a8ddf151-03e3-49d1-b51b-395f5a84cf0f)

to
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/42214b58-d7ec-4e29-9930-a50f02da105b)

```
.img-wrapper {
      width: 50%;
      display: flex;
      justify-content: right;

      img {
        max-height: 70px;
        max-width: 350px;
        cursor: pointer;  
      }
      a {
        justify-content: right;
      }
    }
```

**Comment by matej-kaska** [comment]
Však jste to chtěli takhle

**Comment by jmoravec01** [comment]
Wtf fakt jo 😆

**Comment by matej-kaska** [comment]
jo

**Comment by matej-kaska** [comment]
Should be fixed

**Comment by jmoravec01** [comment]
I don´t think so. There is still missing 
` a {
        justify-content: right;
      }`

without
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/c325563c-7b55-481a-99c8-fc5e580a143d)

with
![image](https://github.com/matej-kaska/ujepsoft/assets/91320507/8e9834dd-8cf7-4683-b969-16c00e784f01)
