### ISSUE TITLE
Weird Displaying of Text in "Nabídky" on Linux Firefox

### ISSUE THREAD

**Issue by Boubik** [matej-kaska/ujepsoft#23]
Description:

I'm encountering an issue where the text is displayed incorrectly in the "Nabídky" section when using Linux Firefox. Please see the attached screenshots for reference.

Steps to Reproduce:

    Navigate to the "Nabídky" section on UJEP Soft.
    Use Linux Firefox to view the page.

Expected Behavior:
The text should display correctly without any formatting issues.

Actual Behavior:
The text is displayed weirdly, as shown in the screenshots.

Screenshots:

Screenshot 1:
![Screenshot 2024-05-16 at 21-35-25 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/ffa544b1-8d4d-4cf0-9c06-ef6ee0e1dbf0)

Screenshot 2:
![Screenshot 2024-05-16 at 21-35-20 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/4aa511a0-72ef-43d2-b073-f81d528cab6a)

Environment:

    OS: Linux
    Browser: Firefox
    
Text:

	Feel free to replace the placeholder text (e.g., "path/to/uploaded/screenshot", "Browser Name and Version", "Operating System Name and Version") with the appropriate details before submitting the issue on GitHub.😀

Please let me know if you need any further information to resolve this issue.

**Comment by matej-kaska** [comment]
Nice catch, should be fixed.

**Comment by Boubik** [comment]
Thank you for addressing the issue. However, it seems that the problem is not fully resolved. The text is still the same as before, but the styling has changed. I made a clean build of the app to ensure accurate testing, but the issue persists.

![Screenshot 2024-05-19 at 13-43-10 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/3efbfbf0-26a4-46ed-a6ac-d3b8effcde7e)
![Screenshot 2024-05-19 at 13-44-56 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/6a6a4f42-db09-43fa-b517-2cff8f4135bb)

**Comment by matej-kaska** [comment]
Could you give me css of the unit-description?

![image](https://github.com/matej-kaska/ujepsoft/assets/12019437/e45fef7d-4b1f-468f-bcd7-46ec8c4ddbed)

**Comment by Boubik** [comment]
It appears there is more content than you have displayed (min-height: 56px; max-height: 56px;)

display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  padding-inline: 0.25rem;
  min-height: 56px;
  max-height: 56px;
  overflow: hidden;
  overflow-wrap: anywhere;
}

**Comment by Boubik** [comment]
Okay, I just tested issue #29, and it is fixed now. The min-height and max-height properties are no longer present.

**Comment by Boubik** [comment]
It changed the formatting in the 'Nabídky' section, so it no longer matches the formatting in the original 'Nabídka'.

![Screenshot 2024-05-19 at 18-40-57 UJEP Soft](https://github.com/matej-kaska/ujepsoft/assets/30127367/9de497dd-8691-4fa8-931a-58eebe6a795c)
